import { ComponentProps } from 'react';
import DecompositionTable from '../DecompositionTable';

const objectId = '9e267f06-6072-4db9-ba0e-e4adccafa0a9';

export const documents: ComponentProps<typeof DecompositionTable>['rows'] = [
	{
		id: 1,
		name: 'Hoofddraagconstructie',
		code: '147',
		location: 'Amsterdam Centrum',
		isStructural: false,
		isElectrical: false,
		constructionYear: 1979,
		isArchived: false,
		isRelevant: true,
		objectId,
	},
	{
		id: 2,
		name: 'Kerende constructie',
		code: '157',
		location: 'Amsterdam Centrum',
		isStructural: false,
		isElectrical: false,
		constructionYear: 1979,
		isArchived: false,
		isRelevant: true,
		objectId,
	},
	{
		id: 3,
		name: 'Brandblusinstallatie',
		code: '119',
		location: 'Amsterdam Centrum',
		isStructural: false,
		isElectrical: false,
		constructionYear: 1979,
		isArchived: false,
		isRelevant: true,
		objectId,
	},
	{
		id: 1,
		elementId: 1,
		name: 'Afdekplaat',
		code: '2049',
		location: 'Amsterdam Centrum',
		material: 'Cementbeton',
		quantity: 1,
		quantityUnitOfMeasurement: 'm2',
		constructionYear: 1979,
		isStructural: true,
		isElectrical: false,
		isRelevant: false,
		isArchived: false,
		objectId,
	},
	{
		id: 2,
		elementId: 2,
		name: 'Langsligger',
		code: '1328',
		location: 'Amsterdam Centrum',
		material: 'Beton',
		quantity: 3,
		quantityUnitOfMeasurement: 'm2',
		constructionYear: 1979,
		isStructural: true,
		isElectrical: false,
		isRelevant: false,
		isArchived: false,
		objectId,
	},
	{
		id: 3,
		elementId: 3,
		name: 'Leuningafwerking',
		code: '2145',
		location: 'Amsterdam Centrum',
		material: 'Onbekend',
		quantity: 5,
		quantityUnitOfMeasurement: 'pcs',
		constructionYear: 1980,
		isStructural: false,
		isElectrical: false,
		isRelevant: false,
		isArchived: false,
		objectId,
	}
];
