name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - '**'
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 14.x ]
                job: [ lint, 'ci:test', 'build:storybook' ]
        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: install
                run: npm ci

            -   name: build
                run: npm run build

            -   name: Run ${{ matrix.job }}
                run: npm run ${{ matrix.job }}
