name: Publish to NPM

on:
    push:
#        branches: [main]
        # TMP
        branches:
            - '**'

    pull_request:
        branches:
            - '**'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 14.x ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                    fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: NPM Install
                run: npm ci

            -   name: Build
                run: npm run build

            -   name: Setup git credentials
                run: |
                    git config --local user.email "github-actions[bot]@noreply.amsterdam.nl"
                    git config --local user.name "github-actions[bot]"

            -   name: Prepare canary release
                if: github.ref != 'refs/heads/master'
                run: npm run release -- --prerelease canary --no-verify

            -   name: Prepare production release
                if: github.ref == 'refs/heads/master'
                run: npm run release -- --no-verify

            -   name: Status
                run: |
                    git remote -v
                    git status
                    git show --summary

            -   name: Push release commit + tag
                uses: ad-m/github-push-action@master
                with:
                    tags: true
                    github_token: ${{ secrets.GITHUB_TOKEN }}
#                    branch: ${{ github.ref }}

            -   name: Publish Canary release to NPM
                if: github.ref != 'refs/heads/master'
                run: |
                    echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
                    npm publish --tag canary --access public
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: Publish production release to NPM
                if: github.ref == 'refs/heads/master'
                run: |
                    echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
                    npm publish --access public
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

